"""Build pytest regression fixtures from AFR checkpoints.

This module backs the ``afr-regression-case`` console script. It intentionally
lives outside the primary ``afr`` parser so the fixture generator can stay small,
reviewable, and usable by automation without disturbing the core CLI.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import httpx

from afr.client import AFRAPIError, AFRClient
from afr.types import DEFAULT_API_URL

_SAFE_SLUG_CHARS = re.compile(r"[^A-Za-z0-9_.-]+")


def short(value: str | None, n: int = 8) -> str:
    return (value or "")[:n]


def slugify(value: str | None, default: str = "afr-regression") -> str:
    raw = (value or "").strip()
    slug = _SAFE_SLUG_CHARS.sub("-", raw).strip("-._")
    return slug or default


def resolve_run_id(client: AFRClient, prefix: str) -> str:
    if len(prefix) >= 32:
        return prefix
    matches = [r["id"] for r in client.list_runs(limit=500) if r["id"].startswith(prefix)]
    if len(matches) == 1:
        return matches[0]
    if not matches:
        raise SystemExit(f"error: no run matches id prefix {prefix!r}")
    raise SystemExit(f"error: ambiguous run id prefix {prefix!r} ({len(matches)} matches)")


def resolve_checkpoint_id(client: AFRClient, run_id: str, prefix: str) -> str:
    if len(prefix) >= 32:
        return prefix
    matches = [
        c["id"] for c in client.list_checkpoints(run_id) if c["id"].startswith(prefix)
    ]
    if len(matches) == 1:
        return matches[0]
    if not matches:
        raise SystemExit(f"error: no checkpoint in run {short(run_id)} matches prefix {prefix!r}")
    raise SystemExit(f"error: ambiguous checkpoint prefix {prefix!r} ({len(matches)} matches)")


def build_case_bundle(
    *,
    run: dict[str, Any],
    events: list[dict[str, Any]],
    checkpoints: list[dict[str, Any]],
    checkpoint: dict[str, Any],
    state: dict[str, Any],
    case_name: str,
) -> dict[str, Any]:
    """Return a portable regression fixture for one recorded checkpoint."""
    return {
        "format": "afr.regression_case.v1",
        "case_name": case_name,
        "source": {
            "run_id": run.get("id"),
            "checkpoint_id": checkpoint.get("id"),
            "checkpoint_label": checkpoint.get("label"),
        },
        "run": run,
        "checkpoint": checkpoint,
        "state": state,
        "events": events,
        "checkpoints": checkpoints,
        "contract": {
            "purpose": "Use the recorded boundary as a reproducible regression fixture.",
            "safe_by_default": True,
            "side_effects": "Do not execute external side effects from this fixture unless the test explicitly mocks or approves them.",
            "expected_operator_step": "Replace the placeholder assertion with the repaired agent behavior.",
        },
    }


def build_test_source(case_name: str) -> str:
    test_name = slugify(case_name, "afr_regression").replace("-", "_").replace(".", "_")
    return f'''"""Regression template generated by `afr-regression-case`.

This test is safe by default. It loads the recorded AFR boundary and gives you a
stable place to assert the repaired behavior. Replace the placeholder assertion
with the agent-specific expectation that should never regress again.
"""

from __future__ import annotations

import json
from pathlib import Path

CASE_PATH = Path(__file__).with_name("case.json")


def load_case() -> dict:
    return json.loads(CASE_PATH.read_text())


def test_{test_name}_fixture_is_well_formed() -> None:
    case = load_case()

    assert case["format"] == "afr.regression_case.v1"
    assert case["run"]["id"] == case["source"]["run_id"]
    assert case["checkpoint"]["id"] == case["source"]["checkpoint_id"]
    assert isinstance(case["events"], list)
    assert "state" in case


def test_{test_name}_repaired_behavior() -> None:
    case = load_case()

    # Replace this placeholder with your repaired agent assertion.
    # Good targets: final answer, tool policy, state transition, retry behavior,
    # or the absence of a previously observed error.
    assert case["checkpoint"]["id"]
'''


def build_readme(case_name: str, run_id: str, checkpoint_id: str) -> str:
    test_file = f"test_regression_{slugify(case_name, 'afr-regression').replace('-', '_').replace('.', '_')}.py"
    return f"""# AFR regression case: {case_name}

Generated by `afr-regression-case`.

## Source

- Run: `{run_id}`
- Checkpoint: `{checkpoint_id}`

## Files

- `case.json` — portable AFR fixture containing the run, events, checkpoints, selected checkpoint, and reconstructed state.
- `{test_file}` — pytest template with one fixture-shape test and one placeholder repair test.

## Use

```bash
python -m pytest . -q
```

The generated test does **not** replay side effects. It gives you a stable fixture so the repaired behavior can be asserted in code.
"""


def write_case_files(
    out_dir: Path,
    *,
    case: dict[str, Any],
    case_name: str,
    force: bool = False,
) -> list[Path]:
    if out_dir.exists() and any(out_dir.iterdir()) and not force:
        raise SystemExit(f"error: output directory is not empty: {out_dir} (pass --force to overwrite)")
    out_dir.mkdir(parents=True, exist_ok=True)

    test_slug = slugify(case_name, "afr-regression").replace("-", "_").replace(".", "_")
    files = {
        "case.json": json.dumps(case, indent=2, default=str) + "\n",
        f"test_regression_{test_slug}.py": build_test_source(case_name),
        "README.md": build_readme(
            case_name,
            str(case["source"]["run_id"]),
            str(case["source"]["checkpoint_id"]),
        ),
    }

    written: list[Path] = []
    for name, content in files.items():
        path = out_dir / name
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="afr-regression-case",
        description="Template a pytest regression case from an AFR checkpoint.",
    )
    parser.add_argument("run_id", help="run id or unique prefix")
    parser.add_argument("--from", dest="from_checkpoint", required=True, metavar="CHECKPOINT", help="checkpoint id or unique prefix")
    parser.add_argument("-A", "--api-url", default=DEFAULT_API_URL, help="AFR backend URL")
    parser.add_argument("-o", "--output", help="output directory")
    parser.add_argument("--name", help="case name (defaults to run/checkpoint prefix)")
    parser.add_argument("--force", action="store_true", help="overwrite files in an existing output directory")
    parser.add_argument("--json", action="store_true", help="emit raw JSON")
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)

    try:
        with AFRClient(args.api_url) as client:
            run_id = resolve_run_id(client, args.run_id)
            checkpoint_id = resolve_checkpoint_id(client, run_id, args.from_checkpoint)
            run = client.get_run(run_id)
            events = client.list_events(run_id, limit=10000)
            checkpoints = client.list_checkpoints(run_id)
            checkpoint = next((c for c in checkpoints if c["id"] == checkpoint_id), None)
            if checkpoint is None:
                raise SystemExit(f"error: checkpoint not found after resolution: {checkpoint_id}")
            state = client.state_at(run_id, checkpoint_id, reconstruct=True)
    except AFRAPIError as exc:
        raise SystemExit(f"error: {exc}") from exc
    except httpx.ConnectError as exc:
        raise SystemExit("error: cannot reach the AFR backend — is it running?") from exc
    except httpx.HTTPError as exc:
        raise SystemExit(f"error: request failed: {exc}") from exc

    case_name = args.name or f"{short(run_id)}-{short(checkpoint_id)}"
    out_dir = Path(args.output or f"afr-regression-{slugify(case_name)}")
    case = build_case_bundle(
        run=run,
        events=events,
        checkpoints=checkpoints,
        checkpoint=checkpoint,
        state=state,
        case_name=case_name,
    )
    files = write_case_files(out_dir, case=case, case_name=case_name, force=args.force)

    result = {
        "case_name": case_name,
        "output_dir": str(out_dir),
        "files": [str(path) for path in files],
    }
    if args.json:
        print(json.dumps(result, indent=2))
        return

    print(f"wrote regression case for run {short(run_id)} @ {short(checkpoint_id)}")
    print(f"  dir   : {out_dir}")
    for path in files:
        print(f"  file  : {path}")
    print("  next  : replace the placeholder assertion, then run `python -m pytest`")


if __name__ == "__main__":
    main()
